version: '2'
services:
  econi:
    restart: unless-stopped
    image: econi:latest
    container_name: econi
    command: java -jar /econi/api-0.0.1-SNAPSHOT.jar
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment:
      - ECONI_PORT=9000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=EcoNI

  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
